import type { BOM, WorkOrder } from './types';

export const MOCK_BOMS: BOM[] = [
  {
    id: 'bom-001',
    product_code: 'BHS-001',
    product_name: 'Bàn học sinh',
    notes: 'Định mức tiêu chuẩn bàn học sinh đơn',
    created_at: '2026-04-15',
    is_active: true,
    items: [
      { id: 'bi-001', item_code: 'TO-D25', item_name: 'Thép ống D25', quantity: 4, unit: 'cái' },
      { id: 'bi-002', item_code: 'GV-01', item_name: 'Gỗ ván MDF 18mm', quantity: 1, unit: 'tấm' },
      { id: 'bi-003', item_code: 'OV-M6', item_name: 'Ốc vít M6', quantity: 16, unit: 'cái' },
      { id: 'bi-004', item_code: 'SN-01', item_name: 'Sơn tĩnh điện xanh', quantity: 0.5, unit: 'kg' },
    ],
  },
  {
    id: 'bom-002',
    product_code: 'GX-101',
    product_name: 'Ghế xoay văn phòng',
    notes: 'Phiên bản cải tiến, đệm dày hơn',
    created_at: '2026-05-02',
    is_active: true,
    items: [
      { id: 'bi-005', item_code: 'KG-01', item_name: 'Khung ghế thép', quantity: 1, unit: 'bộ' },
      { id: 'bi-006', item_code: 'DM-02', item_name: 'Đệm mút D40', quantity: 2, unit: 'tấm' },
      { id: 'bi-007', item_code: 'BX-01', item_name: 'Bánh xe ghế', quantity: 5, unit: 'cái' },
      { id: 'bi-008', item_code: 'TL-01', item_name: 'Ty lực khí nén', quantity: 1, unit: 'cái' },
    ],
  },
  {
    id: 'bom-003',
    product_code: 'TK-200',
    product_name: 'Tủ khóa 6 ngăn',
    notes: 'Tủ khóa thép cho trường học',
    created_at: '2026-05-10',
    is_active: true,
    items: [
      { id: 'bi-009', item_code: 'TH-08', item_name: 'Thép tấm 0.8mm', quantity: 3, unit: 'tấm' },
      { id: 'bi-010', item_code: 'KH-01', item_name: 'Khóa cam', quantity: 6, unit: 'cái' },
      { id: 'bi-011', item_code: 'BL-01', item_name: 'Bản lề', quantity: 12, unit: 'cái' },
    ],
  },
];

export const MOCK_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'wo-001',
    code: 'WO-2026-001',
    product_name: 'Bàn học sinh',
    bom_id: 'bom-001',
    quantity_required: 100,
    quantity_completed: 100,
    status: 'completed',
    planned_start: '2026-04-20',
    planned_end: '2026-05-01',
    actual_end: '2026-04-29',
    created_at: '2026-04-18',
  },
  {
    id: 'wo-002',
    code: 'WO-2026-002',
    product_name: 'Ghế xoay văn phòng',
    bom_id: 'bom-002',
    quantity_required: 50,
    quantity_completed: 20,
    status: 'in_progress',
    planned_start: '2026-05-05',
    planned_end: '2026-05-20',
    created_at: '2026-05-03',
  },
  {
    id: 'wo-003',
    code: 'WO-2026-003',
    product_name: 'Tủ khóa 6 ngăn',
    bom_id: 'bom-003',
    quantity_required: 30,
    quantity_completed: 0,
    status: 'not_started',
    planned_start: '2026-05-18',
    planned_end: '2026-06-01',
    created_at: '2026-05-14',
  },
];
